blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blogs', BlogListView.as_view(), name='blogs'),
    path('blog/view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='blog_view'),
    path('blog/edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from mailing.apps import MailingConfig
from mailing.views import (MainView, MailingCreateView, MailingListView, MailingDetailView, MailingUpdateView,
                           MailingDeleteView, MessageCreateView, MessageListView, MessageUpdateView, MessageDeleteView,
                           ClientCreateView, ClientListView, ClientUpdateView, ClientDeleteView, LogsListView)

app_name = MailingConfig.name

urlpatterns = [
    path('', cache_page(60)(MainView.as_view()), name='main'),
    path('mailing/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailings/', MailingListView.as_view(), name='mailings'),
    path('mailing/detail/<int:pk>', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing/update/<int:pk>', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing/delete/<int:pk>', MailingDeleteView.as_view(), name='mailing_delete'),

    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('messages/', MessageListView.as_view(), name='messages'),
    path('message/update/<int:pk>', MessageUpdateView.as_view(), name='message_update'),
    path('message/delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),

    path('client/create/', ClientCreateView.as_view(), name='client_create'),
    path('clients/', ClientListView.as_view(), name='clients'),
    path('client/update/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('client/delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),

    path('logs/', LogsListView.as_view(), name='logs')
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, ProfileView, ProfileDeleteView, gen_password, verify

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/delete/<int:pk>', ProfileDeleteView.as_view(), name='profile_delete'),
    path('profile/gen_password/', gen_password, name='gen_password'),
    path('verify/<code>/', verify, name='verify_email'),
]

mailing/models.py
from django.db import models
from django.utils import timezone

from config import settings

NULLABLE = {'null': True, 'blank': True}


class Mailing(models.Model):
    PERIOD = (
        ('DAILY', 'Каждый день'),
        ('WEEKLY', 'Каждую неделю'),
        ('MONTHLY', 'Каждый месяц'),
    )

    start_to_send = models.TimeField(verbose_name='Время начало отправки', default=timezone.now)
    stop_to_send = models.TimeField(verbose_name='Время окончания отправки', default=timezone.now)
    periodicity = models.CharField(max_length=50, verbose_name='Периодичность', choices=PERIOD)
    is_active = models.BooleanField(max_length=20, verbose_name='Пуск рассылки', default=False)

    client = models.ManyToManyField('Client', verbose_name='Кому')
    message = models.ForeignKey('Message', on_delete=models.CASCADE, verbose_name='Сообщение')
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь', **NULLABLE
    )

    def __str__(self):
        return f'{self.start_to_send}-{self.stop_to_send} {self.periodicity} {self.is_active} {self.client} {self.message}'

    class Meta:
        verbose_name = "Настройка"
        verbose_name_plural = "Настройки"


class Message(models.Model):
    head = models.CharField(max_length=100, verbose_name='Тема')
    body = models.TextField(verbose_name='Сообщение')

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь', **NULLABLE
    )

    def __str__(self):
        return f'{self.head} {self.body}'

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"


class Client(models.Model):
    email = models.EmailField(unique=True, verbose_name='Email')
    fio = models.CharField(max_length=100, verbose_name='ФИО', **NULLABLE)
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Владелец', **NULLABLE
    )

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"


class Logs(models.Model):
    STATUSES = (
        ('OK', 'Успешно'),
        ('FAILED', 'Ошибка'),
    )

    last_try = models.DateTimeField(verbose_name='Время последней попытки', auto_now_add=True)
    status_try = models.CharField(max_length=50, choices=STATUSES, verbose_name='Статус попытки', default='Успешно')
    answer = models.CharField(max_length=250, verbose_name='Ответ сервера', **NULLABLE)

    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='Рассылка')
    client = models.EmailField(max_length=150, verbose_name='Email клиента', **NULLABLE)

    def __str__(self):
        return f'{self.last_try} {self.status_try} {self.mailing} {self.client}'

    class Meta:
        verbose_name = "Лог"
        verbose_name_plural = "Логи"

mailing/forms.py
from django import forms
from mailing.models import Mailing, Message, Client


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):

    def __init__(self, *args, **kwargs):
        uid = kwargs.pop('uid')
        super().__init__(*args, **kwargs)
        self.fields['client'].queryset = Client.objects.filter(user=uid)
        self.fields['message'].queryset = Message.objects.filter(user=uid)

    class Meta:
        model = Mailing
        exclude = ('user',)


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        exclude = ('user',)


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        exclude = ('user',)

mailing/views.py
import random

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import Http404
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.models import Blog
from mailing.forms import MailingForm, MessageForm, ClientForm
from mailing.models import Mailing, Message, Client, Logs
from mailing.services import get_cache_clients, get_cache_messages


class MainView(LoginRequiredMixin, TemplateView):
    template_name = 'mailing/main.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Главная'

        context_data['mailing'] = len(Mailing.objects.all())
        context_data['started_mailing'] = Mailing.objects.filter(is_active=True).count()
        context_data['client'] = len(Client.objects.all())
        context_data['object_list'] = random.sample(list(Blog.objects.all()), 0)
        return context_data


class MailingCreateView(CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailings')

    def form_valid(self, form):
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'uid': self.request.user.id})
        return kwargs


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Список рассылок'
        return context

    def get_queryset(self):
        if self.request.user.is_staff or self.request.user.has_perm('mailing.view_mailing'):
            return Mailing.objects.all()
        queryset = Mailing.objects.filter(user=self.request.user, is_active=True)
        return queryset


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object


class MailingUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailings')
    permission_required = 'mailing.change_mailing'

    def has_permission(self):
        obj = self.get_object()
        if self.request.user == obj.user or self.request.user.is_staff:
            return True
        return super().has_permission()

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'uid': self.request.user.id})
        return kwargs

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:mailings')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object


class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:messages')

    def form_valid(self, form):
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class MessageListView(LoginRequiredMixin, ListView):
    model = Message

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = get_cache_messages()
        context['title'] = 'Список сообщений'
        return context

    def get_queryset(self):
        if self.request.user.is_staff:
            return Message.objects.all()
        queryset = Message.objects.filter(user=self.request.user)
        return queryset


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:messages')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('mailing:messages')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object


class ClientCreateView(CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:clients')

    def form_valid(self, form):
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class ClientListView(LoginRequiredMixin, ListView):
    model = Client

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = get_cache_clients()
        context_data['title'] = 'Список клиентов'
        return context_data

    def get_queryset(self):
        if self.request.user.is_staff:
            return Client.objects.all()
        queryset = Client.objects.filter(mailing__user=self.request.user)
        return queryset


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:clients')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:clients')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object


class LogsListView(LoginRequiredMixin, ListView):
    model = Logs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Отчет об отправленных рассылках'
        return context

    def get_queryset(self):
        if self.request.user.is_staff:
            return Logs.objects.all()
        queryset = Logs.objects.filter(mailing__user=self.request.user)
        return queryset

mailing/templates/mailing/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">{{ title }}</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'mailing:main' %}">Главная</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'mailing:mailings' %}">Рассылки</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'mailing:messages' %}">Письма</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'mailing:clients' %}">Клиенты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'mailing:logs' %}">Статистика</a>
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Профиль</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выход</a>
        {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Вход</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>

<div class="container">
    {% block content %}
    {% endblock %}
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Удаление клиента
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p>Действительно хотите удалить клиента {{ object.email }}?</p>
                <button type="submit" class="btn btn-outline-danger">
                    Удалить
                </button>
                <a class="btn btn-outline-warning" href="{% url 'mailing:clients' %}">Отмена</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

mailing/templates/mailing/client_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                <h3 class="my-0 font-weight-normal">Редактирование клиента</h3>
                {% else %}
                <h3 class="my-0 font-weight-normal">Добавление клиента</h3>
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn-lg btn-block btn-outline-success">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Добавить
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="row">
    <div class="col-12 mb-5">
        <a href="{% url 'mailing:client_create' %}" class="btn btn-primary"> Создать клиента </a>
    </div>
    {% for object in object_list %}
    <div class="col-md-5">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.email }}</h4>
        </div>
        <div class="card-body">
            <div class="card-body">
                <p class="card-text">{{ object.fio | default:"-" | title}}</p>
                <p class="card-text">{{ object.comment | default:"-" }}</p>
            </div>
            <div class="card-footer">
                {% if user.is_authenticated %}
                <a class="btn btn-primary" href="{% url 'mailing:client_update' object.pk %}">Изменить</a>
                <a class="btn btn-outline-danger float-right" href="{% url 'mailing:client_delete' object.pk %}">Удалить</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

mailing/templates/mailing/logs_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="row">
    {% for object in object_list %}
    <div class="col-4">
        <div class="card shadow-sm">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Рассылка: {{object.mailing_id.message.head}}</h4>
            </div>
            <div class="card-body">
                <p class="card-text">Время последней рассылки: {{object.last_try}}</p>
                <p class="card-text">Статус: {{object.status_try }}</p>
                <p class="card-text">Ответ сервера: {{object.answer|default:'Успешно'}}</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Удаление рассылки
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p>Действительно хотите удалить эту рассылку?</p>
                <button type="submit" class="btn btn-outline-danger">
                    Удалить
                </button>
                <a class="btn btn-outline-warning" href="{% url 'mailing:mailings' %}">Отмена</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}
{% block content %}

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    <div class="col">
        <div class="card shadow-sm">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Тема:{{object.message.head}}</h4>
            </div>
            <div class="card-body">
                <p class="card-text">Сообщение: {{object.message.body}}</p>
                <p class="card-text">Пользователь: {{object.user|default:'Неизвестный пользователь'}}</p>
                <p class="card-text">Время рассылки: {{ object.start_to_send}} - {{ object.stop_to_send}}</p>
                <p class="card-text">Периодичность: {{ object.periodicity}}</p>
                {% if object.is_active %}
                    <p class="card-text">Статус: Активна</p>
                {% else %}
                    <p class="card-text">Статус: Неактивна</p>
                {% endif %}
                <p class="card-text">КОМУ:
                    {% for client in object.client.all %}
                        <p class="card-text">{{client}}</p>
                    {% endfor %}
                <a href="{% url 'mailing:mailings' %}" type="button"
                   class="btn btn-sm btn-outline-secondary">Назад</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                <h3 class="my-0 font-weight-normal">Редактирование рассылки</h3>
                {% else %}
                <h3 class="my-0 font-weight-normal">Создание рассылки</h3>
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn-lg btn-block btn-outline-success">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Добавить
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="row">
    <div class="col-12 mb-5">
        <a href="{% url 'mailing:mailing_create' %}" class="btn btn-primary my-2">Создать рассылку</a>
    </div>
    {% for object in object_list %}
    <div class="col-md-5">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.message.head }}</h4>
        </div>
        <div class="card-body">
            <div class="card-body">
                <p class="card-text">Время начало отправки: {{ object.start_to_send }}</p>
                <p class="card-text">Время окончания отправки: {{ object.stop_to_send }}</p>
                <p class="card-text">Периодичность: {{ object.periodicity }}</p>
                {% if object.is_active %}
                    <p class="card-text">Статус: Активна</p>
                {% else %}
                    <p class="card-text">Статус: Неактивна</p>
                {% endif %}
            </div>
            <div class="card-footer">
                <a class="btn btn-block btn-outline-primary" href="{% url 'mailing:mailing_detail' object.pk %}">Посмотреть</a>
                <a class="btn btn-primary" href="{% url 'mailing:mailing_update' object.pk %}">Изменить</a>
                <a class="btn btn-outline-danger float-right" href="{% url 'mailing:mailing_delete' object.pk %}">Удалить</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

mailing/templates/mailing/main.html
{% extends 'mailing/base.html' %}
{% load my_tags %}

{% block content %}
<div class="container-fluid">
    <div class="row text-center">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Количество рассылок всего</td>
                            <td>{{ mailing }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Количество активных рассылок</td>
                            <td>{{ started_mailing }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Количество уникальных клиентов для рассылок</td>
                            <td>{{ client }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
{% for object in object_list %}
<div class="row text-center">
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="card-title pricing-card-title">{{object.title|title}}</h4>
            </div>
            <div class="card-body">
                <p class="my-0 font-weight-normal">{{object.content|default:"-"|truncatechars:100}}</p>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>Просмотры: {{object.views}}</li>
                    <li>Дата публикации: {{object.date_of_creation}}</li>
                </ul>
                <div class="card-footer">
                    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:blog_view' object.pk %}">Посмотреть</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}


{% endblock %}

mailing/templates/mailing/message_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Удаление письма
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p>Действительно хотите удалить письмо ({{ object.head }})?</p>
                <button type="submit" class="btn btn-outline-danger">
                    Удалить
                </button>
                <a class="btn btn-outline-warning" href="{% url 'mailing:messages' %}">Отмена</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

mailing/templates/mailing/message_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                <h3 class="my-0 font-weight-normal">Редактирование сообщения</h3>
                {% else %}
                <h3 class="my-0 font-weight-normal">Создание сообщения</h3>
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn-lg btn-block btn-outline-success">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Добавить
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="row">
    <div class="col-12 mb-5">
        <a href="{% url 'mailing:message_create' %}" class="btn btn-primary"> Создать письмо </a>
    </div>
    {% for object in object_list %}
    <div class="col-md-5">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.head }}</h4>
        </div>
        <div class="card-body">
            <div class="card-body">
                <p class="card-text">{{ object.body| truncatechars:100 }}</p>
            </div>
            <div class="card-footer">
                <a class="btn btn-primary" href="{% url 'mailing:message_update' object.pk %}">Изменить</a>
                <a class="btn btn-outline-danger float-right" href="{% url 'mailing:message_delete' object.pk %}">Удалить</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}