blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blogs', BlogListView.as_view(), name='blogs'),
    path('blog/view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='blog_view'),
    path('blog/edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from mailing.models import NULLABLE


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=100, verbose_name='slug', **NULLABLE)
    content = models.TextField(verbose_name='содержимое', **NULLABLE)
    preview = models.ImageField(upload_to='blog/', verbose_name='превью', **NULLABLE)
    date_of_creation = models.DateTimeField(verbose_name='дата создания', **NULLABLE)
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views = models.IntegerField(default=0, verbose_name='просмотры')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блог'

blog/forms.py
from django import forms
from mailing.forms import StyleFormMixin
from blog.models import Blog


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        exclude = ('slug', 'is_published', 'views')

blog/views.py
from pytils.translit import slugify
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from blog.models import Blog
from blog.forms import BlogForm


class BlogCreateView(CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blogs')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    form_class = BlogForm

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:blog_view', args=[self.kwargs.get('pk')])


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views += 1
        self.object.save()
        return self.object


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blogs')

blog/templates/blog/blog_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
    <form method="post" class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Удаление Статьи
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    <p>Действительно хотите удалить эту статью ?</p>
                    <button type="submit" class="btn btn-outline-danger">
                        Удалить
                    </button>
                    <a class="btn btn-outline-warning" href="{% url 'blog:blog_view' object.pk %}">Отмена</a>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'mailing/base.html' %}
{% load my_tags %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card mb-4 box-shadow">
                <img class="card-img-top"
                     src="{{ object.preview | media }}"
                     alt="Card image cap">
                <div class="card-body">
                    <p class="card-text">{{ object.title }}</p>
                    <p class="card-text">{{ object.content }}</p>
                </div>
                <div class="card-footer">
                    <a class="btn btn-primary" href="{% url 'blog:blog_edit' object.pk %}">Изменить</a>
                    <a class="btn btn-danger float-right" href="{% url 'blog:blog_delete' object.pk %}">Удалить</a><br>
                    <span class="text-muted">Просмотры: {{ object.views }}</span>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <form method="post" class="row" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    {% if object %}
                        <h3 class="my-0 font-weight-normal">Редактирование Блога</h3>
                    {% else %}
                        <h3 class="my-0 font-weight-normal">Добавление Блога</h3>
                    {% endif %}
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn-lg btn-block btn-outline-success">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Добавить
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'mailing/base.html' %}
{% load my_tags %}

{% block content %}
    <div class="row">
        <div class="col-12 mb-5">
            <a class="btn btn-primary" href="{% url 'blog:blog_create' %}">Написать Статью</a>
        </div>
        {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top"
                         src="{{object.preview|media}}"
                         alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">{{ object.title|title }}</p>
                        <span class="text-muted">{{ object.content|default:"-"|truncatechars:100 }}</span><br>
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:blog_view' object.pk %}">Посмотреть</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}