blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blogs', BlogListView.as_view(), name='blogs'),
    path('blog/view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='blog_view'),
    path('blog/edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, ProfileView, ProfileDeleteView, gen_password, verify

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/delete/<int:pk>', ProfileDeleteView.as_view(), name='profile_delete'),
    path('profile/gen_password/', gen_password, name='gen_password'),
    path('verify/<code>/', verify, name='verify_email'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from mailing.models import NULLABLE


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='Email')
    fio = models.CharField(max_length=100, verbose_name='ФИО', **NULLABLE)

    is_active = models.BooleanField(verbose_name='активный пользователь', default=False)
    verify_code = models.CharField(max_length=50, verbose_name='Верификация')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from mailing.forms import StyleFormMixin

from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'password', 'fio')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random
import secrets

from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView

from django.shortcuts import redirect, render
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse

from users.forms import UserRegisterForm, UserForm
from users.models import User
from users.services import send_verify_code, send_password


class LoginView(BaseLoginView):
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    template_name = 'users/logout.html'


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:verify_email', args=['code'])
    template_name = 'users/register.html'

    def form_valid(self, form):
        if form.is_valid():
            new_user = form.save(commit=False)
            code = secrets.token_urlsafe(nbytes=8)
            new_user.verify_code = code
            new_user.save()
            url_email = self.request.build_absolute_uri(reverse('users:verify_email', args=[code]))
            send_verify_code(new_user, url_email)
        return super().form_valid(form)


def verify(request, code):
    try:
        user = User.objects.get(verify_code=code)
        user.is_active = True
        user.save()
        return redirect(reverse('users:login'))
    except User.DoesNotExist:
        return render(request, 'users/verify.html')


def gen_password(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        user = User.objects.get(email=email)
        new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
        send_password(user.email, new_password)
        user.set_password(new_password)
        user.save()
        return redirect(reverse('users:login'))
    return render(request, 'users/password.html')


class ProfileView(UpdateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class ProfileDeleteView(DeleteView):
    model = User
    success_url = reverse_lazy('users:register')

users/templates/users/login.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="my-0 font-weight-normal">Вход</h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Войти</button>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'users:gen_password' %}" class="btn btn-lg btn-block btn-outline-danger">Забыли
                            пароль?</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/password.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="my-0 font-weight-normal">Восстановление доступа</h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        <input type="text" name="email" class="form-control" id="name" placeholder="Ваш email"><br>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Сгенерировать пароль</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="my-0 font-weight-normal">Регистрация</h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Создать</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/user_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
    <form method="post" class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Удаление профиля
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    <p>Действительно хотите удалить свой профиль?</p>
                    <button type="submit" class="btn btn-outline-danger">
                        Удалить
                    </button>
                    <a class="btn btn-outline-warning" href="{% url 'users:profile' %}">Отмена</a>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="my-0 font-weight-normal">Мой Профиль</h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Сохранить</button>
                        <a class="btn btn-lg btn-block btn-outline-danger" href="{% url 'users:profile_delete' object.pk %}">Удалить</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/verify.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <h4>На ваш email отправлена ссылка для подтверждения регистрации.</h4>
    </div>
{% endblock %}